# Generated by Django 5.1.7 on 2025-03-25 15:28

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='companysettings',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=20),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='text_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
