# Generated by Django 5.1.7 on 2025-03-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers_companysettings_secondary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseToBuy',
            fields=[
                ('price', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('time_to_complete', models.IntegerField()),
                ('language', models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('UA', 'Ukrainian'), ('SE', 'Swedish'), ('DE', 'German'), ('FR', 'French'), ('IT', 'Italian'), ('ES', 'Spanish')], max_length=2)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
