# Generated by Django 5.1.7 on 2025-03-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coursetobuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetobuy',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
