# Generated by Django 5.1.7 on 2025-03-26 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_courses', to='api.company')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_courses', to='api.coursetobuy')),
            ],
            options={
                'unique_together': {('company', 'course')},
            },
        ),
    ]
