# Generated by Django 5.1.7 on 2025-03-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_companysettings_background_color'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
